url: 'https://nyu-dh.github.io'
baseurl: '/website-media'

exclude: [README.md]

defaults:
  - scope:
      path: "files"
    values:
      media: true
  - scope:
      path: "files/banners"
    values:
      banner: true
  - scope:
      path: "files/icons"
    values:
      icon: true
  - scope:
      path: "files/news"
    values:
      news: true
  - scope:
      path: "files/people"
    values:
      people: true
  - scope:
      path: "files/projects"
    values:
      project: true